# Generated by Django 4.1.2 on 2022-11-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fetchEventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('edate', models.CharField(max_length=100)),
                ('estime', models.CharField(max_length=100)),
                ('eetime', models.CharField(max_length=100)),
                ('eorg', models.CharField(max_length=100)),
                ('edesc', models.CharField(max_length=100)),
                ('evenue', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'event_record',
            },
        ),
    ]
